version: '3'

services:
  api:
    container_name: library-management-api
    image: library-management-api-image
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/api:/usr/src/api
      - ./src/api/node_modules:/usr/src/api/node_modules
    depends_on:
      - db

  db:
    container_name: library-management-db
    image: postgres:15.7
    env_file:
      - ./docker/.env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    container_name: library-management-pgadmin
    image: dpage/pgadmin4:8.12
    env_file:
      - ./docker/.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgresdata:
    driver: local
  pgadmin_data:
    driver: local
